FROM ubuntu:16.04
FROM python:3.5
RUN pip install ptvsd
RUN pip install virtualenv

#after this line, add test.py is added under this directory
WORKDIR dockerremotedebug:/mywork

ADD test.py test.py


#-y means when yes/no is prompted, it will say yet to it
#RUN apt-get update
#RUN apt-get -y install build-essential cmake
#RUN apt-get -y install libopenblas-dev liblapack-dev 
#RUN apt-get -y install libx11-dev libgtk-3-dev
#RUN apt-get -y install python python-dev python-pip
#RUN apt-get -y install python3 python3-dev python3-pip
#
#RUN virtualenv dlib_test -p python3
#RUN cd dlib_test
#RUN pip install numpy
#RUN pip install dlib








#RUN apt-get update && apt-get install -y openssh-server
#RUN mkdir /var/run/sshd
#
#RUN echo 'root:kingdom1011' | chpasswd
#
#RUN echo 'root:screencast' | chpasswd
#RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#

#RUN sed -ri 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
#RUN sed -ri 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#RUN sed -ri 's/^UsePAM yes/UsePAM no/' /etc/ssh/sshd_config


# SSH login fix. Otherwise user is kicked off after login
#RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
#RUN service ssh reload
#ENV NOTVISIBLE "in users profile"
#RUN echo "export VISIBLE=now" >> /etc/profile

#EXPOSE 22
#CMD ["/usr/sbin/sshd", "-D"]
#

CMD ["python", "test.py"]